version: "3.8"
services:
  broker:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  payment-service:
    image: order-app/payment-service:0.0.1-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  stock-service:
    image: order-app/stock-service:0.0.1-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
