version: "3.8"
services:
  broker:
    image: apache/kafka:4.0.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=broker
  payment-service:
    image: order-app/payment-service:0.0.1-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
  order-service:
    image: order-app/order-service:0.0.1-SNAPSHOT
    links:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker
